cars/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cars import views
from django.urls import reverse

app_name = 'cars'


urlpatterns = [
    path('catalog/', views.catalog, name = 'catalog'),
    path('catalog/fresh/', views.fresh_cars, name = 'fresh_cars'),
    path('catalog/used/', views.used_cars, name = 'used_cars'),
    path('<int:id>/', views.the_car, name='the_car'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views
from django.urls import reverse

from .views import custom_404_view, custom_500_view



app_name = 'main'


urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('guarantee/', views.guarantee, name = 'guarantee'),
    path('insurance/', views.insurance, name = 'insurance'),
    path('jurists/', views.jurists, name = 'jurists'),
    path('privacy/', views.privacy, name = 'privacy'),
    path('service/', views.service, name = 'service'),
    path('spares/', views.spares, name = 'spares'),

]


handler404 = 'main.views.custom_404_view'
handler500 = 'main.views.custom_500_view'

rg/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

from main import urls
from cars import urls



admin.site.site_header = 'Система Централизованного Управления Контентом'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('', include('main.urls')),
]


urlpatterns += static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

cars/models.py
from django.db import models


class Brand(models.Model):
	id_brand = models.AutoField(primary_key=True)
	brand = models.CharField(max_length=30, verbose_name='Марка', default='Audi')
	class Meta:
		ordering = ['brand']
		indexes = [
			models.Index(fields=['brand']),
		]
		verbose_name = 'Марка'
		verbose_name_plural = 'Марка'	

	def __str__(self):
		return self.brand


class Category(models.Model):
	id_cat = models.AutoField(primary_key=True)
	category = models.CharField(max_length=60, verbose_name='Категория')
	class Meta:
		ordering = ['category']
		indexes = [
			models.Index(fields=['category']),
		]
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'	

	def __str__(self):
		return self.category


class Status(models.Model):
	id_st = models.AutoField(primary_key=True)
	status = models.CharField(max_length=60, verbose_name='Новая / С пробегом')
	class Meta:
		ordering = ['status']
		indexes = [
			models.Index(fields=['status']),
		]
		verbose_name = 'Новая / С пробегом'
		verbose_name_plural = 'Новая / С пробегом'	

	def __str__(self):
		return self.status


class Color(models.Model):
	color_id = models.AutoField(primary_key=True)
	color_name = models.CharField(max_length=50, verbose_name = 'Название цвета', default='Бежевый', null=True)
	color_code = models.CharField(max_length=50, verbose_name = 'Цвет в #HEX', default='#E5E1DF', null=True)

	class Meta:
		ordering = ['color_name']
		indexes = [
			models.Index(fields=['color_name']),
		]
		verbose_name = 'Цвет HEX или RGBA'
		verbose_name_plural = 'Цвета HEX или RGBA'
	def __str__(self):
		return self.color_name


class Car(models.Model):
	id = models.AutoField(primary_key=True)
	category = models.ForeignKey(Category,
		related_name='categories',
		on_delete=models.CASCADE, verbose_name = 'Категория')
	status = models.ForeignKey(Status,
		related_name='statuses',
		on_delete=models.CASCADE, verbose_name = 'Новая/Уже нет')
	color = models.ForeignKey(Color,
		related_name='colors',
		on_delete=models.CASCADE, verbose_name = 'Цвет', null=True)
	brand = models.ForeignKey(Brand,
		related_name='brands',
		on_delete=models.CASCADE, verbose_name = 'Марка', null=True)

	name = models.CharField(max_length=250, null=True, blank=True, verbose_name = 'Название модели')
	price = models.IntegerField(null=True, blank=True, verbose_name = 'Цена')
	price_old = models.IntegerField(null=True, blank=True, verbose_name = 'Цена БЕЗ скидки')
	year = models.CharField(max_length=4, null=True, blank=True, verbose_name = 'Год выпуска')
	engine = models.CharField(max_length=20, null=True, blank=True, verbose_name = 'Двигатель, л/с')
	mileage = models.CharField(max_length=20, null=True, blank=True, verbose_name = 'Пробег')
	transmission = models.CharField(max_length=50, null=True, blank=True, verbose_name = 'Трансмиссия')
	drive = models.CharField(max_length=50, null=True, blank=True, verbose_name = 'Привод')

	main_img = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото главное')
	img_1 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 1')
	img_2 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 2')
	img_3 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 3')
	img_4 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 4')
	img_5 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 5')
	img_6 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 6')
	img_7 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 7')
	img_8 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 8')
	img_9 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 9')
	img_10 = models.ImageField(upload_to='cars/', null=True, blank=True, verbose_name = 'Фото 10')

	available = models.BooleanField(default=True)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']
		indexes = [
			models.Index(fields=['id', 'name']),
		]
		verbose_name = 'Авто'
		verbose_name_plural = 'Авто'





###############

# ABOUT FORMS #

###############





class CallMe(models.Model):
	id = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=30)
	phone = models.CharField(max_length=30)
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')

	class Meta:
		ordering = ['-created']
		verbose_name = 'Заявка: перезвоните мне'
		verbose_name_plural = 'Заявки: перезвоните мне'
	def __str__(self):
		return self.first_name



class WantThisCar(models.Model):
	id = models.AutoField(primary_key=True)
	car_name = models.CharField(max_length=100, verbose_name = 'Марка машины')
	first_name = models.CharField(max_length=30, verbose_name = 'Имя')
	phone = models.CharField(max_length=30, verbose_name = 'Телефон')
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')
	
	class Meta:
		ordering = ['-created']
		verbose_name = 'Хочу такую же'
		verbose_name_plural = 'Запросы: хочу такую же!'

	def __str__(self):
		return self.first_name



class CarSurveyFull(models.Model):
	id = models.AutoField(primary_key=True)
	car_characteristics =  models.TextField(verbose_name = 'Марка, модель, мотор', null=True, blank=True)
	country = models.CharField(max_length=50, verbose_name = 'Из какой страны Вас интересует автомобиль?', null=True, blank=True)
	when =  models.CharField(max_length=50, verbose_name = 'Когда планируете покупать? ', null=True, blank=True)
	payment_type =  models.CharField(max_length=50, verbose_name = 'Форма оплаты за автомобиль?', null=True, blank=True)
	max_price =  models.CharField(max_length=300, verbose_name = 'Максимальный бюджет для покупки?', null=True, blank=True)
	trade_in =  models.CharField(max_length=300, verbose_name = 'Планируете трейд ин? Какой авто? Пробег?', null=True, blank=True)
	complectation =  models.TextField(max_length=600, verbose_name = 'Комплектация?', null=True, blank=True)
	colors =  models.CharField(max_length=100, verbose_name = 'Желаемые цвета кузова и салона', null=True, blank=True)
	need_casco = models.BooleanField(verbose_name = 'Планируете ли делать Каско?', default=True)
	real_price =  models.CharField(max_length=100, verbose_name = 'Какова стоимость реального предложения автомобиля, которое Вам удалось найти?', null=True, blank=True)

	first_name = models.CharField(max_length=30, verbose_name = 'Имя')
	phone = models.CharField(max_length=30, verbose_name = 'Телефон')
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')
	

	class Meta:
		ordering = ['-created']
		verbose_name = 'Заказ машины: подробный опросник'
		verbose_name_plural = 'Заказ машины: подробный опросник'

	def __str__(self):
		return self.first_name



class GuaranteeCount(models.Model):
	id = models.AutoField(primary_key=True)
	who_sold = models.BooleanField(verbose_name = 'Авто куплено через R.E.D. Group?', default=True)
	have_goverment_number = models.BooleanField(verbose_name = 'Есть ли Гос. номер?', default=True)
	goverment_number = models.CharField(max_length=30, verbose_name = 'Если да, укажите:', null=True, blank=True)
	is_gai_record = models.BooleanField(verbose_name = 'Поставлена ли машина на учёт?', default=True)
	first_name = models.CharField(max_length=30, verbose_name = 'Имя')
	phone = models.CharField(max_length=30, verbose_name = 'Телефон')
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')
	
	class Meta:
		ordering = ['-created']
		verbose_name = 'Заявка на рассчет тех.поддержки'
		verbose_name_plural = 'Заявки на рассчет тех.поддержки'

	def __str__(self):
		return self.first_name



class NeedDiagnostic(models.Model):
	id = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=30, verbose_name = 'Имя')
	phone = models.CharField(max_length=30, verbose_name = 'Телефон')
	urgency = models.BooleanField(verbose_name = 'Срочно?', default=False)
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')
	
	class Meta:
		ordering = ['-created']
		verbose_name = 'Заявка на диагностику'
		verbose_name_plural = 'Заявки на диагностику'

	def __str__(self):
		return self.first_name



class NeedServece(models.Model):
	id = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=30, verbose_name = 'Имя')
	phone = models.CharField(max_length=30, verbose_name = 'Телефон')
	urgency = models.BooleanField(verbose_name = 'Срочно?', default=False)
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')
	
	class Meta:
		ordering = ['-created']
		verbose_name = 'Заявка на сервисное обслуживание'
		verbose_name_plural = 'Заявки на сервисное обслуживание'

	def __str__(self):
		return self.first_name



class ShesterenkyNeed(models.Model):
	id = models.AutoField(primary_key=True)
	year = models.CharField(max_length=30, verbose_name = 'Год выпуска', null=True, blank=True)
	vin = models.CharField(max_length=30, verbose_name = 'VIN-номер', null=True, blank=True)
	its_name = models.CharField(max_length=100, verbose_name = 'Название детали', null=True, blank=True)
	img = models.ImageField(upload_to='spares/', null=True, blank=True, verbose_name = 'Фото детали')

	first_name = models.CharField(max_length=30, verbose_name = 'Имя')
	phone = models.CharField(max_length=30, verbose_name = 'Телефон')
	created = models.DateTimeField(auto_now_add=True, verbose_name = 'Заявка поступила')

	class Meta:
		ordering = ['-created']
		verbose_name = 'Заявка на запчасть'
		verbose_name_plural = 'Заявки на запчасти'

	def __str__(self):
		return self.first_name



class CascoCount(models.Model):
	id = models.AutoField(primary_key=True)
	budget =  models.CharField(max_length=30, verbose_name = 'Какой бюджет?')

cars/views.py
import os
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, F, Count, Value
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template

from .models import *
from .forms import *
from .forms_generator import *
from .filters import *
from .tasks import * 


def catalog(request):
	sort_by = request.GET.get('sort_by', 'asc')
	cars = Car.objects.all()
	cars = cars_ordering(Car, cars, sort_by)
	
	queryset = cars
	

	if request.method == 'GET':
		filtered_queryset = cars_filtering(request, queryset)
		print(filtered_queryset)
		if filtered_queryset.exists():
			queryset = filtered_queryset
		else:
			queryset = None

	unique_values = unique_names(request)

	status = request.GET.get('status')
	if status:
		status = int(status)
		cars = cars.filter(status=status)


	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)

	context = {
		'cars' : cars,
		'queryset': queryset,
		'unique_brand': unique_values['unique_brand'],
		'unique_color': unique_values['unique_color'],
		'unique_year': unique_values['unique_year'],
		'unique_transmission': unique_values['unique_transmission'],
		'unique_drive': unique_values['unique_drive'],

		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form
	}

	return render(request, 'cars/catalog.html', context)



def fresh_cars(request):
	sort_by = request.GET.get('sort_by', 'asc')
	cars = Car.objects.filter(status=1)
	cars = cars_ordering(Car, cars, sort_by)
	used_cars = Car.objects.filter(status=2)

	queryset = cars
	
	if request.method == 'GET':
		filtered_queryset = cars_filtering(request, queryset)
		print(filtered_queryset)
		if filtered_queryset.exists():
			queryset = filtered_queryset
		else:
			queryset = None
	unique_values = unique_names(request)


	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)

	context = {
		'cars' : cars,
		'used_cars': used_cars,
		'queryset': queryset,
		'unique_brand': unique_values['unique_brand'],
		'unique_color': unique_values['unique_color'],
		'unique_year': unique_values['unique_year'],
		'unique_transmission': unique_values['unique_transmission'],
		'unique_drive': unique_values['unique_drive'],

		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form
	}

	return render(request, 'cars/fresh.html', context)



def used_cars(request):
	sort_by = request.GET.get('sort_by', 'asc')
	cars = Car.objects.filter(status=2)	
	cars = cars_ordering(Car, cars, sort_by)
	new_cars = Car.objects.filter(status=1)

	queryset = cars
	if request.method == 'GET':
		filtered_queryset = cars_filtering(request, queryset)
		print(filtered_queryset)
		if filtered_queryset.exists():
			queryset = filtered_queryset
		else:
			queryset = None
	unique_values = unique_names(request)


	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)


	context = {
		'cars':cars,
		'new_cars': new_cars,
		'queryset': queryset,
		'unique_brand': unique_values['unique_brand'],
		'unique_color': unique_values['unique_color'],
		'unique_year': unique_values['unique_year'],
		'unique_transmission': unique_values['unique_transmission'],
		'unique_drive': unique_values['unique_drive'],

		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form
	}

	return render(request, 'cars/used.html', context)



def the_car(request, id):		
	if id:
		the_car = get_object_or_404(Car, id=id)
		similar_cars = Car.objects.filter(category=the_car.category)
		new_cars = Car.objects.filter(status=1)
		used_cars = Car.objects.filter(status=2)


	callme_form = CallMeForm()
	want_this_car_form = WantThisCarForm()
	car_survey_full_form = CarSurveyFullForm()
	casco_count_form = CascoCountForm()
	
	want_this_car = None

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'want_this_car':
			want_this_car = handle_want_this_car_form(request)
			print(want_this_car_form.errors) 
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)
		elif form_type == 'casco_count':
			casco_count_form = handle_casco_count_form(request)


	context = {
		'the_car': the_car,
		'similar_cars': similar_cars,
		'new_cars': new_cars,
		'used_cars': used_cars,

		'callme_form': callme_form,
		'want_this_car_form': want_this_car_form,
		'car_survey_full_form': car_survey_full_form,
		'casco_count_form': casco_count_form
	}
	return render(request, 'cars/the_car.html', context)

cars/templates/cars/popups/btn_wa.html
{% load static %}

<a href='https://wa.me/79052226226'>
  	<button class='btn_whatsapp'>
	    <div class="d-flex justify-content-start">
			<img loading="" class="pe-2 tg_btn_icon" src="{% static 'icons/whatsapp_white.png' %}">
			<span class="pt-1">Чат в WhatsApp</span>
	 	</div>
	</button>
</a>

cars/templates/cars/popups/form_popup.html
 {% load static %}
 <div class='modal_container' onclick='showModal(this);'>
    
    <div class='button_form_base mt-3 mb-5 py-2'>Подбор авто</div>

    <div class='modal_full hide'>
      <span class="close" onclick="closeModal(this);">&times;</span>

      <div class=''>
        
        <form method="post" class="callme_container white_bg">
          <img class='w-100 p-5' src='{% static "brand/logo.svg" %}'>
          <div class='form_container we_300'>
            <h3 class='pb-3'>Заказать звонок</h3>

            {{ callme_form.as_p }}
            
            {% csrf_token %}
          
          <center class='py-3'><input type="submit" value="Получить консультацию" class="button_dark"></center>

          <p class='pt-3 smaller'>* Нажимая на кнопку "Получить консультацию", Вы соглашаетесь с <u><a class='gray_dark' href='{% url "main:privacy" %}'>Политикой конфиденциальности</a></u>.</p>
          </div>
        </form>

      </div>
    </div>
  </div>

cars/templates/cars/popups/popup_guarantee.html
{% load static %}
<style type="text/css">
    #id_who_sold{
    width: 1.2em;
    height: 1.2em;
    margin: .5em;
    padding: .3em 0 0 0;
  }
  #id_have_goverment_number{
    width: 1.2em;
    height: 1.2em;
    margin: .5em;
    padding: .3em 0 0 0;
  }
  #id_is_gai_record {
    width: 1.2em;
    height: 1.2em;
    margin: .5em;
    padding: .3em 0 0 0;
  }
</style>

<div class='modal_container' onclick='showModal(this);'>
  <button class='thumb button_form_base mt-3 mb-2 black'>Хочу оформить</button>

    <div class='modal_full hide'>
      <div class=''>
        
        <form method="post" class="callme_container white_dirty_bg">
          <div class='d-flex flex-row-reverse pe-3'>
            <span class="close" onclick="closeModal(this);">&times;</span>
          </div>

          <center>
             <img class='popup_big_logo' src='{% static "brand/logo.svg" %}'>
          </center>
          <h3 class='we_300 ms-4'>ЗАЯВКА НА ОФОРМЛЕНИЕ <span class='red'>ТЕХНИЧЕСКОЙ ПОДДЕРЖКИ</span></h3>
          <div class='form_container we_300'>

            <div class='d-flex justify-content-start py-2'>
              {{ guarantee_count_form.who_sold }}
              <label class='ps-2' for="{{ guarantee_count_form.who_sold.id_for_label }}">{{ guarantee_count_form.who_sold.label }}</label>
              
            </div>

            <div class='d-flex justify-content-start py-2'>
              {{ guarantee_count_form.have_goverment_number }}
              <label class='ps-3 pt-2' for="{{ guarantee_count_form.have_goverment_number.id_for_label }}">{{ guarantee_count_form.have_goverment_number.label }}</label>
            </div>

            <label class='px-2' for="{{ guarantee_count_form.goverment_number.id_for_label }}">{{ guarantee_count_form.goverment_number.label }}</label>
            {{ guarantee_count_form.goverment_number }}


            <div class='d-flex justify-content-start py-2'>
              {{ guarantee_count_form.is_gai_record }}
              <label class='ps-3 pt-2' for="{{ guarantee_count_form.is_gai_record.id_for_label }}">{{ guarantee_count_form.is_gai_record.label }}</label>
           
            </div>

            <br>
            <label class='' for="{{ guarantee_count_form.first_name.id_for_label }}">{{ guarantee_count_form.first_name.label }}</label>
            {{ guarantee_count_form.first_name }}

            <label class='pt-2' for="{{ guarantee_count_form.phone.id_for_label }}">{{ guarantee_count_form.phone.label }}</label>
            {{ guarantee_count_form.phone }}

            {% csrf_token %}

            <input type="hidden" name="form_type" value="guarantee_count">
            <center class='pt-5 pb-3'><input type="submit" value="Перезвоните мне" class="button_dark"></center>

            <p class='pt-3 smaller'>* Нажимая на кнопку "Перезвоните мне",<br>Вы соглашаетесь с <u><a class='gray_dark' href='{% url "main:privacy" %}'>Политикой конфиденциальности</a></u>.</p>
          </div>
        </form>

      </div>
    </div>
</div>

cars/templates/cars/popups/popup_need_diagnostic.html
{% load static %}
<style type="text/css">
    #id_urgency{
    width: 1.2em;
    height: 1.2em;
    margin: .5em;
    padding: .3em 0 0 0;
  }
</style>

<div class='modal_container' onclick='showModal(this);'>
  <button class='thumb button_form_base black'>Записаться на диагностику</button>

    <div class='modal_full hide'>
      <div class=''>

        <form method="post" class="callme_container white_dirty_bg">
          <div class='d-flex flex-row-reverse pe-3'>
            <span class="close" onclick="closeModal(this);">&times;</span>
          </div>

          <center><img class='popup_big_logo' src='{% static "brand/logo.svg" %}'></center>
          
          <h2 class='we_300 ms-4'>ЗАПИСЬ НА ДИАГНОСТИКУ</h2>

          <div class='form_container we_300'>

            <label for="{{ need_diagnostic_form.first_name.id_for_label }}">{{ need_diagnostic_form.first_name.label }}</label>
            {{ need_diagnostic_form.first_name }}

            <label class='pt-2' for="{{ need_diagnostic_form.phone.id_for_label }}">{{ need_diagnostic_form.phone.label }}</label>
            {{ need_diagnostic_form.phone }}

            <div class='d-flex justify-content-start py-2'>
              {{ need_diagnostic_form.urgency }}
              <label class='pt-1' for="{{ need_diagnostic_form.urgency.id_for_label }}">Cрочно?</label>   
            </div>
            
            {% csrf_token %}

            <input type="hidden" name="form_type" value="need_diagnostic">
          
            <center class='py-3'><input type="submit" value="Перезвоните мне" class="button_dark"></center>

            <p class='pt-3 smaller'>* Нажимая на кнопку "Перезвоните мне",<br>Вы соглашаетесь с <u><a class='gray_dark' href='{% url "main:privacy" %}'>Политикой конфиденциальности</a></u>.</p>
          </div>
        </form>

      </div>
    </div>
</div>

cars/templates/cars/popups/popup_survey_full.html
{% load static %}

<style>
  #id_need_casco{
    width: 1.2em;
    height: 1.2em;
    margin: .5em;
    padding: .3em 0 0 0;
  }
</style>

<div class='modal_container' onclick='showModal(this);'>
  <button class='thumb button_form_base mt-3 mb-2 black'>Заполнить заявку на подбор</button>

    <div class='modal_full hide'>
      <div class=''>

        <form method="post" class="callme_container white_dirty_bg">
          <div class='d-flex flex-row-reverse pe-3'>
            <span class="close" onclick="closeModal(this);">&times;</span>
          </div>
          
          <center><img class='popup_big_logo' src='{% static "brand/logo.svg" %}'></center>

          <div class='form_container we_300'>

            <label class='' for="{{ car_survey_full_form.car_characteristics.id_for_label }}">Марка, модель, мотор</label>
            {{ car_survey_full_form.car_characteristics }}

            <label class='pt-3' for="{{ car_survey_full_form.country.id_for_label }}">Из какой страны Вас интересует автомобиль?</label>
            {{ car_survey_full_form.country }}

            <label class='pt-3' for="{{ car_survey_full_form.when.id_for_label }}">Когда планируете покупать?</label>
            {{ car_survey_full_form.when }}

            <label class='pt-3' for="{{ car_survey_full_form.payment_type.id_for_label }}">Форма оплаты за автомобиль?</label>
            {{ car_survey_full_form.payment_type }}

            <label class='' for="{{ car_survey_full_form.max_price.id_for_label }}">Максимальный бюджет для покупки?</label>
            {{ car_survey_full_form.max_price }}

            <label class='pt-3' for="{{ car_survey_full_form.trade_in.id_for_label }}">Планируете трейд ин? Какой авто? Пробег?</label>
            {{ car_survey_full_form.trade_in }}

            <label class='pt-3' for="{{ car_survey_full_form.complectation.id_for_label }}">Желаемая комплектация?</label>
            {{ car_survey_full_form.complectation }}

            <label class='pt-3' for="{{ car_survey_full_form.colors.id_for_label }}">Желаемые цвета кузова и салона</label>
            {{ car_survey_full_form.colors }}


            <div class='d-flex justify-content-start pt-3'>
               {{ car_survey_full_form.need_casco }}
               <label class='pt-1' for="{{ car_survey_full_form.need_casco.id_for_label }}">Планируете ли оформлять КАСКО?</label>
            </div>

            <label class='pt-3' for="{{ car_survey_full_form.real_price.id_for_label }}">Какова стоимость реального предложения автомобиля,<br> которое Вам удалось найти?</label>
            {{ car_survey_full_form.real_price }}

                      
            <label class='pt-3' for="{{ car_survey_full_form.first_name.id_for_label }}">{{ car_survey_full_form.first_name.label }}</label>
            {{ car_survey_full_form.first_name }}

            <label class='pt-3' for="{{ car_survey_full_form.phone.id_for_label }}">{{ car_survey_full_form.phone.label }}</label>
            {{ car_survey_full_form.phone }}
            
            {% csrf_token %}

            <input type="hidden" name="form_type" value="car_survey_full">
            
            <center class='py-3'><input type="submit" value="Получить консультацию" class="button_dark"></center>

            <p class='pt-3 smaller'>* Нажимая на кнопку "Получить консультацию",<br>Вы соглашаетесь с <u><a class='gray_dark' href='{% url "main:privacy" %}'>Политикой конфиденциальности</a></u>.</p>
          </div>
        </form>

      </div>
    </div>
</div>