cars/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cars import views
from django.urls import reverse

app_name = 'cars'


urlpatterns = [
    path('catalog/', views.catalog, name = 'catalog'),
    path('catalog/fresh/', views.fresh_cars, name = 'fresh_cars'),
    path('catalog/used/', views.used_cars, name = 'used_cars'),
    path('<int:id>/', views.the_car, name='the_car'),
]

rg/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

from main import urls
from cars import urls



admin.site.site_header = 'Система Централизованного Управления Контентом'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('', include('main.urls')),
]


urlpatterns += static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

cars/forms.py
from django import forms
from .models import *



class CallMeForm(forms.ModelForm):
	class Meta:
		model = CallMe
		fields = ['first_name', 'phone']
		labels = {
		'first_name': 'Имя',
		'phone': 'Телефон',
		}


class WantThisCarForm(forms.ModelForm):
	class Meta:
		model = WantThisCar
		fields = ['first_name', 'phone', 'car_name']
		labels = {
		'first_name': 'Имя',
		'phone': 'Телефон'
		}
		
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['car_name'].required = False


class CarSurveyFullForm(forms.ModelForm):
	class Meta:
		model = CarSurveyFull
		fields = [
		'car_characteristics',
		'country',
		'when',
		'payment_type',
		'max_price',
		'trade_in',
		'complectation',
		'colors',
		'need_casco',
		'real_price',
		'first_name',
		'phone'
		]
		labels = {
		'car_characteristics': 'Марка, модель, мотор',
		'country': 'Из какой страны вас интересует автомобиль?',
		'when': 'Когда планируете покупку?',
		'payment_type': 'Форма оплаты за автомобиль?',
		'max_price': 'Максимальный бюджет покупки?',
		'trade_in': 'Планируете трейд ин? Какой авто? Пробег?',
		'complectation': 'Какую вы хотите комплектацию?',
		'colors': 'Желаемые цвета кузова и салона',
		'need_casco': 'Планируете оформлять КАСКО?',
		'real_price': 'Какова стоимость реального предложения автомобиля, которое Вам удалось найти?',
		'first_name': 'Имя',
		'phone': 'Телефон'
		}


class GuaranteeCountForm(forms.ModelForm):
	class Meta:
		model = GuaranteeCount
		fields = [
		'who_sold',
		'have_goverment_number',
		'goverment_number',
		'is_gai_record',
		'first_name',
		'phone'
		]
		labels = {
		'who_sold': 'Авто куплено через R.E.D. Group?',
		'have_goverment_number': 'Есть ли Гос. номер?',
		'goverment_number': 'Если да, укажите',
		'is_gai_record': 'Есть регистрация в ГАИ?',
		'first_name': 'Имя',
		'phone': 'Телефон'
		}


class NeedDiagnosticForm(forms.ModelForm):
	class Meta:
		model = NeedDiagnostic
		fields = [
		'first_name',
		'phone',
		'urgency'
		]
		labels = {
		'first_name': 'Имя',
		'phone': 'Телефон',
		'urgency': 'Срочно?',
		}


class NeedServeceForm(forms.ModelForm):
	class Meta:
		model = NeedServece
		fields = [
		'first_name',
		'phone',
		'urgency'
		]
		labels = {
		'first_name': 'Имя',
		'phone': 'Телефон',
		'urgency': 'Срочно?',
		}


class ShesterenkyNeedForm(forms.ModelForm):
	class Meta:
		model = ShesterenkyNeed
		fields = [
		'year',
		'vin',
		'its_name',
		'img',
		'first_name',
		'phone'
		]
		labels = {
		'year': 'Год выпуска',
		'vin': 'VIN-номер',
		'its_name': 'Название',
		'img': 'Фото (если есть)',
		'first_name': 'Имя',
		'phone': 'Телефон'
		}


class CascoCountForm(forms.ModelForm):
	class Meta:
		model = CascoCount
		fields = [
		'budget',
		'type',
		'first_name',
		'phone'
		]
		labels = {
		'budget': 'Бюджет',
		'type': 'Тип',
		'first_name': 'Имя',
		'phone': 'Телефон'
		}


class LegalHelpForm(forms.ModelForm):
	class Meta:
		model = LegalHelp
		fields = [
		'where_auto',
		'documents',
		'first_name',
		'phone'
		]
		labels = {
		'where_auto': 'Где сейчас находится машина?',
		'documents': 'Какие у вас есть документы?',
		'first_name': 'Имя',
		'phone': 'Телефон'
		}

cars/views.py
import os
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, F, Count, Value
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template

from .models import *
from .forms import *
from .forms_generator import *
from .filters import *
from .tasks import * 


def catalog(request):
	sort_by = request.GET.get('sort_by', 'asc')
	cars = Car.objects.all()
	cars = cars_ordering(Car, cars, sort_by)
	
	queryset = cars
	

	if request.method == 'GET':
		filtered_queryset = cars_filtering(request, queryset)
		print(filtered_queryset)
		if filtered_queryset.exists():
			queryset = filtered_queryset
		else:
			queryset = None

	unique_values = unique_names(request)

	status = request.GET.get('status')
	if status:
		status = int(status)
		cars = cars.filter(status=status)


	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)

	context = {
		'cars' : cars,
		'queryset': queryset,
		'unique_brand': unique_values['unique_brand'],
		'unique_color': unique_values['unique_color'],
		'unique_year': unique_values['unique_year'],
		'unique_transmission': unique_values['unique_transmission'],
		'unique_drive': unique_values['unique_drive'],

		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form
	}

	return render(request, 'cars/catalog.html', context)



def fresh_cars(request):
	sort_by = request.GET.get('sort_by', 'asc')
	cars = Car.objects.filter(status=1)
	cars = cars_ordering(Car, cars, sort_by)
	used_cars = Car.objects.filter(status=2)

	queryset = cars
	
	if request.method == 'GET':
		filtered_queryset = cars_filtering(request, queryset)
		print(filtered_queryset)
		if filtered_queryset.exists():
			queryset = filtered_queryset
		else:
			queryset = None
	unique_values = unique_names(request)


	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)

	context = {
		'cars' : cars,
		'used_cars': used_cars,
		'queryset': queryset,
		'unique_brand': unique_values['unique_brand'],
		'unique_color': unique_values['unique_color'],
		'unique_year': unique_values['unique_year'],
		'unique_transmission': unique_values['unique_transmission'],
		'unique_drive': unique_values['unique_drive'],

		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form
	}

	return render(request, 'cars/fresh.html', context)



def used_cars(request):
	sort_by = request.GET.get('sort_by', 'asc')
	cars = Car.objects.filter(status=2)	
	cars = cars_ordering(Car, cars, sort_by)
	new_cars = Car.objects.filter(status=1)

	queryset = cars
	if request.method == 'GET':
		filtered_queryset = cars_filtering(request, queryset)
		print(filtered_queryset)
		if filtered_queryset.exists():
			queryset = filtered_queryset
		else:
			queryset = None
	unique_values = unique_names(request)


	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)


	context = {
		'cars':cars,
		'new_cars': new_cars,
		'queryset': queryset,
		'unique_brand': unique_values['unique_brand'],
		'unique_color': unique_values['unique_color'],
		'unique_year': unique_values['unique_year'],
		'unique_transmission': unique_values['unique_transmission'],
		'unique_drive': unique_values['unique_drive'],

		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form
	}

	return render(request, 'cars/used.html', context)



def the_car(request, id):		
	if id:
		the_car = get_object_or_404(Car, id=id)
		similar_cars = Car.objects.filter(category=the_car.category)
		new_cars = Car.objects.filter(status=1)
		used_cars = Car.objects.filter(status=2)


	callme_form = CallMeForm()
	want_this_car_form = WantThisCarForm()
	car_survey_full_form = CarSurveyFullForm()
	casco_count_form = CascoCountForm()
	
	want_this_car = None

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'want_this_car':
			want_this_car = handle_want_this_car_form(request)
			print(want_this_car_form.errors) 
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)
		elif form_type == 'casco_count':
			casco_count_form = handle_casco_count_form(request)


	context = {
		'the_car': the_car,
		'similar_cars': similar_cars,
		'new_cars': new_cars,
		'used_cars': used_cars,

		'callme_form': callme_form,
		'want_this_car_form': want_this_car_form,
		'car_survey_full_form': car_survey_full_form,
		'casco_count_form': casco_count_form
	}
	return render(request, 'cars/the_car.html', context)

cars/templates/cars/carousel_all.html
<style>

  .owl-theme .owl-dots .owl-dot span {
    width: .25em!important;
    height: 4px!important;
    margin: 5px 7px!important;
    display: block!important;
    -webkit-backface-visibility: visible!important;
    transition: opacity .2s ease!important;
    border-radius: 0!important;
  }

	.owl-prev, .owl-next {
      position:absolute;
   }
  .owl-prev {
      left:0;
      top: 120px;
   }
   .owl-next {
      right:0;
      top:120px;
   }
	.owl-nav{
		padding: 0px 20px;
	}

	.owl-carousel .owl-nav button.owl-next, .owl-carousel .owl-nav button.owl-prev, .owl-carousel button.owl-dot{
		font-family: "Montserrat", sans-serif;
		font-size: 5em;
		color: #a2b5c5;
	}
</style>

<div class="owl-carousel owl-carousel-five py-4">

{% for e in similar_cars %}
	<div class="item">
	  <a href="{% url 'cars:the_car' id=e.id %}">
      <div class='wrap_case_img'>
        <img loading="lazy" src='{{e.main_img.url}}' class='case_prev'>

          <h3 class='car_name black ps-3 pt-2'>{{e.name}}</h3>
          <p class='gray ps-3 pt-2 price_display'>{{e.price}} ₽</p>      

      </div>
    </a>
  </div>
{% endfor %}
</div>

cars/templates/cars/carousel_new.html
<style>

  .owl-theme .owl-dots .owl-dot span {
    width: .25em!important;
    height: 4px!important;
    margin: 5px 7px!important;
    display: block!important;
    -webkit-backface-visibility: visible!important;
    transition: opacity .2s ease!important;
    border-radius: 0!important;
  }

	.owl-prev, .owl-next {
      position:absolute;
   }
  .owl-prev {
      left:0;
      top: 120px;
   }
   .owl-next {
      right:0;
      top:120px;
   }
	.owl-nav{
		padding: 0px 20px;
	}

	.owl-carousel .owl-nav button.owl-next, .owl-carousel .owl-nav button.owl-prev, .owl-carousel button.owl-dot{
		font-family: "Montserrat", sans-serif;
		font-size: 5em;
		color: #a2b5c5;
	}
</style>

<div class="owl-carousel owl-carousel-five py-4">

{% for e in new_cars %}
	<div class="item">
	  <a href="{% url 'cars:the_car' id=e.id %}">
      <div class='wrap_case_img'>
        <img loading="lazy" src='{{e.main_img.url}}' class='case_prev'>

          <h3 class='car_name black ps-3 pt-2'>{{e.name}}</h3>
          <p class='gray ps-3 pt-2 price_display'>{{e.price}} ₽</p>      

      </div>
    </a>
  </div>
{% endfor %}
</div>

cars/templates/cars/carousel_the_car.html
<style>

	.owl-theme .owl-dots .owl-dot span {
		width: .25em!important;
		height: 4px!important;
		margin: 5px 7px!important;
		display: block!important;
		-webkit-backface-visibility: visible!important;
		transition: opacity .2s ease!important;
		border-radius: 0!important;
	}
	.owl-prev, .owl-next {
      position:absolute;
   }
  .owl-prev {
      left:0;
      top: 120px;
   }
   .owl-next {
      right:0;
      top:120px;
   }
	.owl-nav{
		padding: 0px 20px;
	}

	.owl-carousel .owl-nav button.owl-next, .owl-carousel .owl-nav button.owl-prev, .owl-carousel button.owl-dot{
		font-family: "Montserrat", sans-serif;
		font-size: 5em;
		color: #a2b5c5;
	}
</style>

<div class="owl-carousel owl-carousel-one-by-one owl-theme">
	<div class="item">
	{% if the_car.img_1 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_1.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_2 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_2.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_3 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_3.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_4 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_4.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_5 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_5.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_6 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_6.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_7 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_7.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_8 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_8.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_9 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_9.url }}">
	{% endif %}
	</div>
	<div class="item">
	{% if the_car.img_10 %}
		<img loading="lazy" class="w-100 car_header" src="{{ the_car.img_10.url }}">
	{% endif %}
	</div>
</div>

cars/templates/cars/carousel_used.html
<style>

  .owl-theme .owl-dots .owl-dot span {
    width: .25em!important;
    height: 4px!important;
    margin: 5px 7px!important;
    display: block!important;
    -webkit-backface-visibility: visible!important;
    transition: opacity .2s ease!important;
    border-radius: 0!important;
  }

	.owl-prev, .owl-next {
      position:absolute;
   }
  .owl-prev {
      left:0;
      top: 120px;
   }
   .owl-next {
      right:0;
      top:120px;
   }
	.owl-nav{
		padding: 0px 20px;
	}

	.owl-carousel .owl-nav button.owl-next, .owl-carousel .owl-nav button.owl-prev, .owl-carousel button.owl-dot{
		font-family: "Montserrat", sans-serif;
		font-size: 5em;
		color: #a2b5c5;
	}
</style>

<div class="owl-carousel owl-carousel-five py-4">

{% for e in used_cars %}
	<div class="item">
	  <a href="{% url 'cars:the_car' id=e.id %}">
      <div class='wrap_case_img'>
        <img loading="lazy" src='{{e.main_img.url}}' class='case_prev'>

          <h3 class='car_name black ps-3 pt-2'>{{e.name}}</h3>
          <p class='gray ps-3 pt-2 price_display'>{{e.price}} ₽</p>      

      </div>
    </a>
  </div>
{% endfor %}
</div>

cars/templates/cars/catalog.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}


{% include 'cars/fun/flip_catalog.html' %}


<div class='desctop_84'>

  <div class='d-none d-lg-block d-xl-block d-xxl-block'>
    <center>
      <h1 class='catalog_h1 red we_300'>ЛУЧШИЕ МАШИНЫ СО ВСЕГО МИРА</h1>
      <h3 class='catalog_sub we_200 pb-3'>В наличии и под заказ</h3>
    </center>
  </div>

  <div class='d-block d-lg-none'>
    <h1 class='catalog_h1 red we_300'>ЛУЧШИЕ МАШИНЫ СО ВСЕГО МИРА</h1>
    <h3 class='pt-2 catalog_sub we_200'>В наличии</h3>
    <h3 class='catalog_sub we_200'>и под заказ</h3>
  </div>
</div>

  <div class="d-flex justify-content-center mt-2">

    <div>{% include 'cars/popups/popup_call_me.html' %}</div>

    <div>
      <div class='button_form_base center mt-3 mb-2 ms-3 white'>
        <div class="d-flex justify-content-start">
          <img loading="lazy" class=' pe-2 tg_btn_icon' src='{% static "icons/telegram_white.png" %}'><span class=''>В наличии</span>
        </div>
      </div>
    </div>
  </div> 



<section id='filters' class="">
  {% include 'cars/filters/filters_light.html' %}
</section>


<div class="desctop_84">

{% if queryset %}

  <div class='cars_container py-5'>

    {% for car in queryset %}

    <a href='{% url "cars:the_car" car.id %}'>
      <div class='wrap_car_img'>
        <img loading="lazy" src='{{car.main_img.url}}' class='case_prev'>
        <h3 class='car_name black ps-3 mt-4'>{{car.name}}</h3>
        <p class='black ps-3 pt-2 price_display'>{{car.price}} ₽</p>
      </div>
    </a>
    {% endfor %}

  </div>

  {% else %}

  <section id='nothing'>
    <div class="d-flex justify-content-start py-2">
      <div>
        <img loading="lazy" class='img_auto' src="{% static 'icons/search_64.png' %}" />
      </div>
      <div class='ps-2'>
        <h1 class='py-3 we_300'>Пожалуйста, измените параметры поиска</h1>
        <h3 class='pb-3 we_200'>Мы пока не добавили авто с такими параметрами в каталог</h3>
      </div>
    </div>   
  </section>

  {% endif %}

</div>

</section>

{% endblock %}

cars/templates/cars/fresh.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class='desctop_84'>
  <h1 class='we_300 h1_24-5 pt-4'>НОВЫЕ МАШИНЫ</h1>
  <h3 class='we_200'>Напрямую с завода</h3>

<!--   <section id='filters' class="">
      {% include 'cars/filters/filters_light.html' %}
    </section> -->

<div class="d-flex justify-content-center">
    <form method="get" class='p-3'>
      <button class="btn_transperent" type="submit" name="sort_by" value="desc">Сначала дорогие ↑</button>
      <button class="btn_transperent" type="submit" name="sort_by" value="asc">Сначала бюджетные ↓</button>
    </form>
    <div class='d-none d-lg-block d-xl-block d-xxl-block py-3'>
      <a class='' href='{% url "cars:used_cars" %}'>
        <button class="btn_transperent" type="" name="" value="asc">Посмотреть авто с пробегом →</button>
      </a>
    </div> 
  </div> 
  <div class='d-block d-lg-none'>
    <a class='p-3' href='{% url "cars:used_cars" %}'>
      <button class="btn_transperent red" type="" name="" value="asc">Посмотреть авто с пробегом →</button>
    </a>
  </div>

  <div class='cars_container py-5'>
    {% for car in cars %}
    <a href='{% url "cars:the_car" car.id %}'>
      <div class='wrap_car_img'>
        <img loading="lazy" src='{{car.main_img.url}}' class='case_prev'>
        <h3 class='car_name black ps-3 mt-4'>{{car.name}}</h3>
        <p class='black ps-3 pt-2 price_display'>{{car.price}} ₽</p>
      </div>
    </a>
    {% endfor %}
  </div>
</div>

<section class="white_dirty_bg">
  <div class="desctop_84 py-3">
    <h2 class='big_h2_guar we_200 pt-5'>МАШИНЫ С ПРОБЕГОМ</h2>
    <h3 class="we_300 red">Из разных точек мира</h3>
  </div>
  {% include 'cars/carousel_used.html' %}
</section>

{% endblock %}

cars/templates/cars/the_car.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}


<section class=''>
	<div class='row'>
		<p class='d-block d-lg-none ps-5 pt-3 pb-1'><a href='{% url "cars:catalog" %}' class='small gray'>Каталог /</a> <a href='{% url "cars:catalog" %}' class='small gray'>{{ the_car.category }}</a></p>

		<div class='col-md-7 pb-4'>
			{% include 'cars/carousel_the_car.html' %}
		</div>

		<div class='col-md-5 pb-4 ps-5'>

			<div class='car_summary'>

				<p class='d-none d-lg-block d-xl-block d-xxl-block pb-4'><a href='{% url "cars:catalog" %}' class='small gray'>Каталог /</a> <a href='{% url "cars:catalog" %}' class='small gray'>Легковые авто</a></p>

				<h1 class='the_car_name'>{{ the_car.name }}</h1>
				<h3 class='the_car_price price_display pt-2 pb-4'>{{ the_car.price }} ₽</h3>

				<table>
					<tbody class='the_car_info'>
						<tr>
							<td><span class='we_500 pe-5'>Год выпуска:</span></td>
							<td>{{ the_car.year }}</td>
						</tr>
						<tr>
							<td><span class='we_500 pe-5'>Двигатель:</span></td>
							<td>{{ the_car.engine }}</td>
						</tr>
						<tr>
							<td><span class='we_500 pe-5'>Пробег:</span></td>
							<td>{{ the_car.mileage }} км</td>
						</tr>
						<tr>
							<td><span class='we_500 pe-5'>Трансмиссия:</span></td>
							<td>{{ the_car.transmission }}</td>
						</tr>
						<tr>
							<td><span class='we_500 pe-5'>Привод:</span></td>
							<td>{{ the_car.drive }}</td>
						</tr>
					</tbody>
				</table>

				<div class='mt-5'>
				{% include 'cars/popups/popup_want_this.html' %}
				</div>
			</div>
		</div>
	</div>
</section>

<section class=''>
	<div class='desctop_84 my-4'>
		<h2 class='we_400 gray the_car_name'>ИНТЕРЕСНЫЕ ВАРИАНТЫ</h2>
	</div>
{% include 'cars/carousel_new.html' %}
</section>


{% include 'cars/banners/banner_want_similar.html' %}


<section class='pt-5'>
	<div class='desctop_84'>
		<div class='d-none d-lg-block d-xl-block d-xxl-block'>
			<br><br>
		</div>


	<div class='d-none d-lg-block d-xl-block d-xxl-block'>
		<div class="d-flex justify-content-start">
			<h2 class='we_200 red the_car_name pe-5'>МАШИНЫ БЕЗ ПРОБЕГА</h2>

			<a href='https://t.me/RedGroupAuto'>
				<button class='button_form_base center mb-2 ms-3 white'>
          <div class="d-flex justify-content-start">
            <img loading="lazy" class='pe-2 tg_btn_icon' src='{% static "icons/telegram_white.png" %}'><span class='white'>Посмотреть, что в наличии</span>
          </div>
        </button>
      </a>

		</div>
	</div>

	<div class='d-block d-lg-none'>
		<h2 class='we_400 red banner_big pb-4'>МАШИНЫ БЕЗ ПРОБЕГА</h2>

			<a href='https://t.me/RedGroupAuto'>
				<button class='button_form_base center mb-2 ms-3 white'>
          <div class="d-flex justify-content-start">
            <img loading="lazy" class='pe-2 tg_btn_icon' src='{% static "icons/telegram_white.png" %}'><span class='white '>Посмотреть, что в наличии</span>
          </div>
        </button>
      </a>
	</div>



	</div>
{% include 'cars/carousel_new.html' %}
</section>

<section>
	{% include 'cars/banners/banner_guarantee_insurance.html' %}
</section>

{% endblock %}

cars/templates/cars/used.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class='desctop_84'>
  <h1 class='we_300 h1_24-5 pt-4'>МАШИНЫ С ПРОБЕГОМ</h1>
  <h3 class='we_200'>Прошли полное ТО в нашей мастерской</h3>

  <div class="d-flex justify-content-center">
    <form method="get" class='p-3'>
      <button class="btn_transperent" type="submit" name="sort_by" value="desc">Сначала дорогие ↑</button>
      <button class="btn_transperent" type="submit" name="sort_by" value="asc">Сначала бюджетные ↓</button>
    </form> 

    <div class='d-none d-lg-block d-xl-block d-xxl-block py-3'>
      <a class='' href='{% url "cars:fresh_cars" %}'>
        <button class="btn_transperent" type="" name="" value="asc">Посмотреть новые машины →</button>
      </a>
    </div>
  </div>

  <div class='d-block d-lg-none'>
    <a class='p-3' href='{% url "cars:fresh_cars" %}'>
      <button class="btn_transperent red" type="" name="" value="asc">Посмотреть новые машины →</button>
    </a>
  </div>



  <div class='cars_container py-5'>
    {% for car in cars %}
    <a href='{% url "cars:the_car" car.id %}'>
      <div class='wrap_car_img'>
        <img loading="lazy" src='{{car.main_img.url}}' class='case_prev'>
        <h3 class='car_name black ps-3 mt-4'>{{car.name}}</h3>
        <p class='black ps-3 pt-2 price_display'>{{car.price}} ₽</p>
      </div>
    </a>
    {% endfor %}
  </div>
</div>

<section class="mt-5 white_dirty_bg">
  <div class="desctop_84 py-3">
    <h2 class='big_h2_guar we_200 pt-5'>НОВЫЕ ИНОМАРКИ</h2>
    <h3 class="we_300 red">Из разных точек мира</h3>
  </div>
  {% include 'cars/carousel_new.html' %}
</section>

{% endblock %}