cars/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cars import views
from django.urls import reverse

app_name = 'cars'


urlpatterns = [
    path('catalog/', views.catalog, name = 'catalog'),
    path('catalog/fresh/', views.fresh_cars, name = 'fresh_cars'),
    path('catalog/used/', views.used_cars, name = 'used_cars'),
    path('<int:id>/', views.the_car, name='the_car'),
]

main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views
from django.urls import reverse

from .views import custom_404_view, custom_500_view



app_name = 'main'


urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('guarantee/', views.guarantee, name = 'guarantee'),
    path('insurance/', views.insurance, name = 'insurance'),
    path('jurists/', views.jurists, name = 'jurists'),
    path('privacy/', views.privacy, name = 'privacy'),
    path('service/', views.service, name = 'service'),
    path('spares/', views.spares, name = 'spares'),

]


handler404 = 'main.views.custom_404_view'
handler500 = 'main.views.custom_500_view'

rg/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

from main import urls
from cars import urls



admin.site.site_header = 'Система Централизованного Управления Контентом'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('', include('main.urls')),
]


urlpatterns += static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

main/models.py
from django.db import models

# Create your models here.

main/views.py
import os
from django.shortcuts import render
from django.conf import settings
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template, render_to_string
from django.urls import reverse

from cars.models import *
from cars.forms import *
from cars.forms_generator import *
from cars.tasks import * 


def custom_404_view(request, exception):
    return render(request, 'main/404.html', status=404)
    
def custom_500_view(request):
    return render(request, 'main/500.html', status=500)


# def index_cover(request):
# 	return render(request, 'main/index_cover.html')

def index(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = handle_callme_form(request)

	context = {
		'callme_form': callme_form,
		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/index.html', context)

def about(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = CallMeForm()
	car_survey_full_form = CarSurveyFullForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')
		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'car_survey_full':
			car_survey_full_form = handle_car_survey_full_form(request)

	context = {
		'callme_form': callme_form,
		'car_survey_full_form': car_survey_full_form,

		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/about.html', context)
	
def contact(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = handle_callme_form(request)

	context = {
		'callme_form': callme_form,
		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/contact.html', context)
	
def guarantee(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = CallMeForm()
	need_diagnostic_form = NeedDiagnosticForm()
	need_service_form = NeedServeceForm()
	guarantee_count_form = GuaranteeCountForm()


	if request.method == 'POST':
		form_type = request.POST.get('form_type')

		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'need_service':
			need_service_form = handle_need_service_form(request)
		elif form_type == 'need_diagnostic':
			need_diagnostic_form = handle_need_diagnostic_form(request)
		elif form_type == 'guarantee_count':	
			guarantee_count_form = handle_guarantee_count_form(request)

	context = {
		'callme_form': callme_form,
		'guarantee_count_form': guarantee_count_form,
		'need_service_form': need_service_form,
		'need_diagnostic_form': need_diagnostic_form,
		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/guarantee.html', context)

def insurance(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = CallMeForm()
	casco_count_form = CascoCountForm()


	if request.method == 'POST':
		form_type = request.POST.get('form_type')

		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'casco_count':
			casco_count_form = handle_casco_count_form(request)


	context = {
		'callme_form': callme_form,
		'casco_count_form': casco_count_form,

		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/insurance.html', context)

def jurists(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = CallMeForm()
	legal_help_form = LegalHelpForm()

	if request.method == 'POST':
		form_type = request.POST.get('form_type')

		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'legal_help':
			legal_help_form = handle_legal_help_form(request)

	context = {
		'callme_form': callme_form,
		'legal_help_form': legal_help_form,

		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/jurists.html', context)

def privacy(request):
	cars = Car.objects.all()
	callme_form = handle_callme_form(request)

	context = {
		'callme_form': callme_form,
		'cars' : cars,
	}
	return render(request, 'main/privacy.html', context)

def service(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = CallMeForm()
	need_diagnostic_form = NeedDiagnosticForm()
	need_service_form = NeedServeceForm()
	
	if request.method == 'POST':
		form_type = request.POST.get('form_type')

		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'need_service':
			need_service_form = handle_need_service_form(request)
		elif form_type == 'need_diagnostic':
			need_diagnostic_form = handle_need_diagnostic_form(request)

	context = {
		'callme_form': callme_form,
		'need_diagnostic_form': need_diagnostic_form,
		'need_service_form': need_service_form,
		
		'cars' : cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/service.html', context)

def spares(request):
	cars = Car.objects.all()
	new_cars = Car.objects.filter(status=1)
	used_cars = Car.objects.filter(status=2)

	callme_form = CallMeForm()
	shesterenky_need_form = ShesterenkyNeedForm()
	need_diagnostic_form = NeedDiagnosticForm()
	need_service_form = NeedServeceForm()


	if request.method == 'POST':
		form_type = request.POST.get('form_type')

		if form_type == 'call_me':
			callme_form = handle_callme_form(request)
		elif form_type == 'shesterenky_need':
			shesterenky_need_form = handle_shesterenky_need_form(request)
		elif form_type == 'need_service':
			need_service_form = handle_need_service_form(request)
		elif form_type == 'need_diagnostic':
			need_diagnostic_form = handle_need_diagnostic_form(request)

	context = {
		'callme_form': callme_form,
		'shesterenky_need_form': shesterenky_need_form,
		'need_diagnostic_form': need_diagnostic_form,
		'need_service_form': need_service_form,

		'cars': cars,
		'new_cars': new_cars,
		'used_cars': used_cars,
	}
	return render(request, 'main/spares.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
  #bez_pyli{
    max-width: 20em;
  }
    /* mobile */
  @media (max-width: 810px) {
    .big_contact{
      font-size: 4em;
    }
  }
    /* desctop */
  @media (min-width: 811px){
    .big_contact{
      font-size: 6em;
    }

  }

  .mesh_dark{
    background-image: url("{% static 'abstract/mesh_dark.png' %}");
  }
</style>

<section class='block_header'>
  {% include 'main/parts/space_about.html' %}
</section>

<div class="gray_light_bg py-3">
  <div class="desctop_84">
    <div class="row">
        <div class="col-md-4">
          <h1 class='big_contact pb-3 pt-3 black we_200'>В ЛИЦАХ</h1>
          <div class="black we_300">
            <p><span class='we_400'>Александр</span> — бизнесмен, автоэксперт, пауэрлифтер</p>
            <p><span class='we_400'>Фёдор</span> — предприниматель и меценат</p>
            <p><span class='we_400'>Дмитрий</span> — инвестор и специалист в сфере недвижимости</p>
            <p><span class='we_400'>Игорь</span> — бизнесмен, арт-критик, ЗОЖник</p>

            <p class="pt-3 we_400">Что нас объединяет?</p>Многолетняя дружба, ставшая основой для нескольких бизнес-проектов. 
            <p>А ещё — тяга исследовать новое. 
            <p>Смотрите свежие выпуски на нашем канале:
          </div>

          <a href='https://youtube.com/@bezpili78?si=kQtvLs9u3OWsO0TR'><img id='bez_pyli' class='my-4' src="{% static 'logos/bez_pyli.png' %}"></a>        
        </div>

        <div class="col-md-8 ">
          <div class='row'>
            <div class="col-md-6">
              <a href='https://youtu.be/zF9lWkOuN6A?si=b2hJf37MOzQInpSx'>
                <img loading="lazy" class='w-100 my-2' src="{% static 'img/zastavky_pokupat_avto_opasno.png' %}">
              </a> 
              <a href='https://youtu.be/mgxgv381kvs?si=ALQw9u05C5TJqLOC'>
                <img loading="lazy" class='w-100 my-2' src="{% static 'img/zastavky_BMW_1.png' %}">
              </a> 
              
            </div>
            <div class="col-md-6">
              <a href='https://youtu.be/PiI6GyoWZUA?si=0Ex9RzBL1H5owJLK'>
                <img loading="lazy" class='w-100 my-2' src="{% static 'img/zastavky_smotrim_2shky.png' %}">
              </a> 
              <a href='https://youtu.be/pC4wmXi2FwU?si=ovb60FdkfVYh5nKm'>
                <img loading="lazy" class='w-100 my-2' src="{% static 'img/zastavky_nude_king.png' %}">
              </a> 
            </div>
          </div>
        </div>
      </div>
    </div>
</div>



{% endblock %}

main/templates/main/base_min.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>R.E.D. Group Auto</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'brand/favicon.ico' %}" >
 
  <!-- <link rel="stylesheet" href='{% static "css/cursor.css" %}'> -->
  <link rel="stylesheet" href='{% static "css/style_main.css" %}'>
  <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
  <link rel="stylesheet" href="{% static 'owl/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'owl/owl.theme.default.min.css' %}">
  


  <!-- Yandex.Metrika counter -->
  <script type="text/javascript" >
     (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
     m[i].l=1*new Date();
     for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
     k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
     (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

     ym(99176486, "init", {
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true
     });
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/99176486" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->


<style>
  .black_bg{
    background-color: var(--black);
  }
  .white{
    color: var(--white);
  }
  #nav_mob {
    transition: background-color 0.3s ease, opacity 0.3s ease;
  }
  .op_it {
    opacity: 0; /* Make it invisible */
}
.menu_mob_list{
  color: var(--white)!important;
}
</style>

</head>
<body>

<header>

  <div id="follower" class="follower"></div>

  <nav id='nav_mob' class=" fixed-top">
    <div class="container-fluid ">
      
      <div class='d-flex justify-content-between mx-4'> 
        <div> 
          <a class="navbar-brand" href='{% url "main:index" %}'>          
              <img class='logo_mob  mt-3' src='{% static "brand/logo_dark.svg" %}'>
          </a>
        </div>
        <div class='pt-4'>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" onclick="add_bg();" onclick="toggleMenuIcon();">
            <img id="menuIcon" class='menu_icon' src="{% static 'icons/menu.png' %}">
          </button>
        </div>
      </div>




      <div class="collapse navbar-collapse" id="navbarNav">

        <!-- DESCTOP -->
        <div class='d-none d-lg-block d-xl-block d-xxl-block black_bg '>
          <div class='row'>
            <div class='col-6'></div>
            <div class='col-6'>

              <ul id='base_min' class="navbar-nav menu_mob_list">

                <li class="nav-item">
                   <a class="nav-link" href='{% url "cars:catalog" %}'>Каталог авто</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href='{% url "main:guarantee" %}'>Оформить гарантию</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href='{% url "main:insurance" %}'>Автострахование</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href='{% url "main:service" %}'>Диагностика & сервис</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href='{% url "main:spares" %}'>Запчасти</a>
                </li>
                <li class="nav-item">
                 <a class="nav-link" href='{% url "main:jurists" %}'>Юридическая поддержка</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href='{% url "main:about" %}'>О нас</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href='{% url "main:contact" %}'>Контакты</a>
                </li>

                  <div class='ps-3 pt-5 modal_container' onclick='showModal(this);'>
                    {% include 'cars/popups/popup_call_me.html' %}
                  </div>


              </ul>
            </div>
          </div>
        </div>

        <!-- PHONE -->
        <div class='d-block d-lg-none '>
        
          <ul class="navbar-nav menu_mob_list">

            <li class="nav-item">
               <a class="nav-link" href='{% url "cars:catalog" %}'>Каталог авто</a>
            </li>
            <li class="nav-item">
               <a class="nav-link ps-2" href='{% url "cars:fresh_cars" %}'><span class='red pe-3'>•</span> Новые</a>
            </li>
            <li class="nav-item">
               <a class="nav-link ps-2" href='{% url "cars:used_cars" %}'><span class='red pe-3'>•</span> С пробегом</a>
            </li>
            <li class="nav-item we_300 ms-2 my-2">——————————</li>
            <li class="nav-item">
              <a class="nav-link" href='{% url "main:guarantee" %}'>Оформить гарантию</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{% url "main:insurance" %}'>Автострахование</a>
            </li>
            <li class="nav-item">
             <a class="nav-link" href='{% url "main:jurists" %}'>Юридическая поддержка</a>
            </li>

            <li class="nav-item we_300 ms-2 my-2">——————————</li>
            <li class="nav-item">
              <a class="nav-link" href='{% url "main:service" %}'>Диагностика & сервис</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{% url "main:spares" %}'>Запчасти</a>
            </li>
            <li class="nav-item we_300 ms-2 my-2">——————————</li>
            <li class="nav-item">
              <a class="nav-link" href='{% url "main:about" %}'>О нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{% url "main:contact" %}'>Контакты</a>
            </li>

            <div class='pt-3 modal_container' onclick='showModal(this);'>
              {% include 'cars/popups/popup_call_me.html' %}
            </div>
          </ul>
        </div>

      </div>

    </div>
  </nav>

</header>


{% block content %}
{% endblock %}

<!-- DESCTOP FOOTER -->
<div class='d-none d-lg-block d-xl-block d-xxl-block'>
  <footer class=' py-4 gray_light we_300 black_hot_bg'>

    <div class='desctop_84'>
      <div class="d-flex justify-content-between">

        <div class=''>
          <a class="" href='{% url "main:index" %}'>
            <div class="center">
              <img class='footer_logo center' src='{% static "brand/logo_dark.svg" %}'>
            </div>
          </a>
        </div>

        <div class='py-3'>
          <a class="nav_footer_mob" href='{% url "cars:catalog" %}'><p>Легковые авто</p></a>
          <a class="nav_footer_mob" href='{% url "cars:catalog" %}'><p>Грузовые машины</p></a>
          <a class="nav_footer_mob" href='{% url "cars:catalog" %}'><p>Автобусы</p></a>
          <a class="nav_footer_mob" href='{% url "cars:catalog" %}'><p>Спецтехника</p></a>
        </div>

        <div class='py-3'>
          <a class="nav_footer_mob" href='{% url "main:insurance" %}'><p>Страхование</p></a>
          <a class="nav_footer_mob" href='{% url "main:guarantee" %}'><p>Оформить гарантию</p></a>
          <a class="nav_footer_mob" href='{% url "main:spares" %}'><p>Диагностика и сервисное обслуживание</p></a>
          <a class="nav_footer_mob" href='{% url "main:jurists" %}'><p>Юридическая поддержка</p></a>
          <a class="nav_footer_mob" href='{% url "main:about" %}'><p>О нас</p></a>
        </div>

        <div class='py-3'>
          <p class="gray_light">+7 921 444‑24‑40</p>
          <p class="gray_light">+7 905 222‑62-26</p>
          <p class="gray_light">info@rgspace.pro</p>


          <div class="d-flex justify-content-start mt-4">
            <a href='https://youtube.com/@bezpili78?si=kQtvLs9u3OWsO0TR'><img class='smm_head pt-1 me-2' src='{% static "icons/youtube_gray.png" %}'></a>
            <a href='https://t.me/RedGroupAuto'><img class='smm_head py-2 me-3' src='{% static "icons/telegram_gray.png" %}'></a>
            <a href='https://wa.me/79052226226'><img class='smm_head py-2' src='{% static "icons/whatsapp_gray.png" %}'></a>
          </div>
        </div>
      </div>
      
      <div class='gray_light smaller we_300'>  
      © 2024, R.E.D. Group Auto. Все права защищены.
      </div>
    </div>
  
  </footer>
</div>

<!-- MOBILE FOOTER -->
<div class='d-block d-lg-none'>
  <footer class='py-4 white black_hot_bg'>

    <div class="d-flex justify-content-between px-4">
      <div class=''>

        <a class="" href='{% url "main:index" %}'>
          <div class="center">
            <img class='footer_logo center' src='{% static "brand/logo_dark.svg" %}'>
          </div>
        </a>

        <p class="nav_footer pt-5 mt-2">+7 921 444‑24‑40</p>
        <p class="nav_footer py-3">+7 905 222‑62-26</p>
        <p class="nav_footer">info@rgspace.pro</p>
      </div>

      <div class='py-3'>
        <a class="nav_footer" href='{% url "cars:catalog" %}'><p>Каталог</p></a>
        <a class="nav_footer" href='{% url "main:insurance" %}'><p >Страхование</p></a>
        <a class="nav_footer" href='{% url "main:guarantee" %}'><p>Оформить гарантию</p></a>
        <a class="nav_footer" href='{% url "main:jurists" %}'><p>Юридическая поддержка</p></a>
        <a class="nav_footer" href='{% url "main:service" %}'><p class='pt-4'>Сервиcное обслуживание</p></a>
        <a class="nav_footer" href='{% url "main:spares" %}'><p>Запчасти</p></a>
        
        <a class="nav_footer" href='{% url "main:about" %}'><p class='pt-4'>О нас</p></a>
        <a class="nav_footer" href='{% url "main:contact" %}'><p>Контакты</p></a>

        <div class="d-flex justify-content-start mt-4">
          <a href='https://youtube.com/@bezpili78?si=kQtvLs9u3OWsO0TR'><img class='smm_head pt-1 me-2' src='{% static "icons/youtube_gray.png" %}'></a>
          <a href='https://t.me/RedGroupAuto'><img class='smm_head py-2 me-3' src='{% static "icons/telegram_gray.png" %}'></a>
          <a href='https://wa.me/79052226226'><img class='smm_head py-2' src='{% static "icons/whatsapp_gray.png" %}'></a>
        </div>
      </div>
    </div>
   
    <center class='mt-3 gray_light smaller we_300'>  
    © 2024, R.E.D. Group Auto. Все права защищены.
    </center>

  </footer>
</div>


<script src='{% static "js/bootstrap.min.js" %}'></script> 
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>


<!-- <script src='{% static "js/cursor.js" %}'></script> -->

<script src='{% static "js/add_space.js" %}'></script>
<script src='{% static "js/modal_form.js" %}'></script>
<script src='{% static "js/toggle_menu.js" %}'></script>

<script src="{% static 'owl/owl.carousel.min.js' %}"></script>



<script type="text/javascript">
  
  let lastScrollTop = 0;
  const navMob = document.getElementById('nav_mob');

  window.addEventListener('scroll', function() {
      const currentScroll = window.pageYOffset || document.documentElement.scrollTop;

      if (currentScroll > lastScrollTop) {
          // Scrolling down
          navMob.classList.add('black_bg');
          navMob.classList.add('white');
          navMob.classList.remove('op_it');
      } else {
          // Scrolling up
          navMob.classList.remove('black_bg');
          navMob.classList.remove('white');
          navMob.classList.add('op_it');
      }

      lastScrollTop = currentScroll <= 0 ? 0 : currentScroll; // For Mobile or negative scrolling
  });


</script>




<script>
  $(document).ready(function(){
    $('.owl-carousel-five').owlCarousel({
      items: 5, // Set the number of items to display in the carousel
      loop: true, // Enable loop
      margin: 10, // Set margin between items
      autoplay: true, // Enable autoplay
      autoplayTimeout: 3000, // Set autoplay timeout
      responsive:{
        0:{
          items:1
        },
        600:{
          items:5
        }
      }
    });
  });
</script>

<script>
  $(document).ready(function(){
    $('.owl-carousel-one-by-one').owlCarousel({
      items: 1, // Set the number of items to display in the carousel
      loop: true, // Enable loop
      margin: 10, // Set margin between items
      autoplay: true, // Enable autoplay
      autoplayTimeout: 3000, // Set autoplay timeout
      responsive:{
        0:{
          items:1
        },
        600:{
          items:1
        }
      }
    });
  });
</script>





</body>
</html>

main/templates/main/email.html
<!doctype html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Новая заявка</title>
    <style media="all" type="text/css">
      table {
      border-collapse: separate;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
      width: 100%;
      }
      body {
        color: #455059;
        margin: 0;
        padding: 0;
      }
      a{
        text-decoration: none;
      }
      .tel{
        font-size: 15px;
      }

      h1, h2, h3, h4 {
        color: #010305;
      }
      h1{
        font-size: 2.3em;
        font-weight: 400;
      }
      h5{
        font-weight: 200;
      }

      td{
        padding: 5px;
      }
      .no_border{
        border: none;
      }

      hr{
        color: #79cbee;
      }
    </style>
</head>

<body>

  <table class='no_border'>
    <thead></thead>
    <tbody>
      <tr>
        <td class='no_border'>
          <a href='https://renovation-rf.ru'><h1>АИК «Реновация»</h1></a>
        </td>
        <td class='no_border'></td> <td class='no_border'></td> <td class='no_border'></td>
        <td class='no_border'>
          <p>
          <strong>Новая заявка на консультацию № {{ callme.id }}</strong>
          <br>
            <span class="secondary">
              {{ callme.created|date:"d M, Y" }}
            </span>
          </p>
        </td>
      </tr>
    </tbody>
  </table>

  <hr>
  <br><br>

  <h3>Контактные данные:</h3>

  <table class='no_border'>
    <thead></thead>
    <tbody>
      <tr>
        <td class='no_border'> <strong>Имя:</strong>
        </td>
        <td class='no_border'>{{ callme.first_name }}</td>
      </tr>
      <tr>
        <td class='no_border'> <strong>Телефон: </strong> 
        </td>
        <td class='no_border'>{{ callme.phone }}</td>
      </tr>
      <tr>
        <td class='no_border'> <strong>E-mail:  </strong>
        </td>
        <td class='no_border'>{{ callme.email }}</td>
      </tr>

    </tbody>
  </table>
   <br><br>
  <center><h4>Сезгә яхшы көн телим!</h4></center>
  
  <br><br><br>

</body>
</html>